### ISSUE TITLE
Problems with build.xml

### ISSUE THREAD

**Issue by rvcristiand** [VisualComputing/framesjs#10]
Hi !

When I try to do

> ant 

in the 

> \framesjs\resources\ 

folder I got the next message

> BUILD FAILED
> .\framesjs\resources\build.xml:108: The following error occurred while executing this line:
> .\framesjs\resources\build.xml:142: .\Users\admin\.lib\p5-3x does not exist.

I have a Windows 7 Ultimate x64 and Ant(TM) version 1.10.3 compiled on March 24 2018.

**Comment by rvcristiand** [comment]
I created all the folders necessary for compile the project and I got these news messages (I modified the new message for simplicity)

Danilinho@Danilinho-PC MINGW64 /d/framesjs/resources (processing)
$ ant
Buildfile: D:\framesjs\resources\build.xml

init:
     [echo] ------------------------------------------------------------------------------------------------
     [echo]     Building the Processing Library frames 4
     [echo] ------------------------------------------------------------------------------------------------
     [echo]     src path        D:\framesjs\src
     [echo]     bin path        D:\framesjs\bin
     [echo]     classpath.local C:\Users\Danilinho/.lib/p5-3x
     [echo]     sketchbook      C:\Users\Danilinho/sketchbook
     [echo]     java version    1.8
     [echo] ------------------------------------------------------------------------------------------------
     [echo]

library.init:
     [echo] init library ...

library.run:
     [echo] building library ...

generate.structure:

    ...

generate.source:

generate.source.win:
     [echo] generating source (windows) ...

parse.file:
     [echo] D:\framesjs\tmp\frames\src\frames\core\Frame.java

    ...

generate.source.nix:

compile:
    [javac] Compiling 35 source files to D:\framesjs\bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] D:\framesjs\tmp\frames\src\frames\processing\GLMatrixHandler.java:16: error: package processing.core does not exist
    [javac] import processing.core.PMatrix3D;
    [javac]                       ^
    [javac] D:\framesjs\tmp\frames\src\frames\processing\GLMatrixHandler.java:17: error: package processing.opengl does not exist

    ...

    [javac]       py = (float) Math.sin(PApplet.radians(i * degrees)) * radius;
    [javac]            ^
    [javac] D:\framesjs\tmp\frames\src\frames\processing\Scene.java:1625: warning: [cast] redundant cast to float
    [javac]       px = (float) Math.cos(PApplet.radians(i * degrees)) * radius;
    [javac]            ^
    [javac] D:\framesjs\tmp\frames\src\frames\processing\Scene.java:1626: warning: [cast] redundant cast to float
    [javac]       py = (float) Math.sin(PApplet.radians(i * degrees)) * radius;
    [javac]            ^
    [javac] 100 errors
    [javac] 10 warnings

BUILD FAILED
D:\framesjs\resources\build.xml:107: The following error occurred while executing this line:
D:\framesjs\resources\build.xml:141: Compile failed; see the compiler error output for details.

Total time: 8 seconds

**Comment by nakednous** [comment]
p5-3x is an [IntellijIdea library](https://www.jetbrains.com/help/idea/libraries-and-global-libraries.html). Just update it to reflect your local path.

**Comment by rvcristiand** [comment]
Thank you so much !

**Comment by rvcristiand** [comment]
I import the library framejs and the processing's core to my project. It's necessary copy the [PickingBuffer.frag](https://github.com/VisualComputing/framesjs/blob/processing/data/PickingBuffer.frag) file in the personal project or it will not compile. Thanks to @eccarrilloe for the tip !
