### ISSUE TITLE
Problems with the frame's visit method

### ISSUE THREAD

**Issue by rvcristiand** [VisualComputing/framesjs#9]
Hi !
I did a new class from the [frame ](https://github.com/VisualComputing/framesjs/blob/geom/src/frames/core/Frame.java) class and I override the visit method

`  @Override
  void visit() {
    pushStyle();
    noStroke();
    fill(sphereColor());
    sphere(sphereSize());
    popStyle();

    Vector iScreen = scene().screenLocation(position());

    if (drawEtiqueta()) {
      scene().beginScreenDrawing();
      pushStyle();
      textAlign(CENTER, CENTER);
      textSize(etiquetaSize());  // problemas
      fill(etiquetaColor());
      text(etiqueta(), iScreen.x() + etiquetaSize(), iScreen.y() - etiquetaSize());  // problemas
      popStyle();
      scene().endScreenDrawing();
    }
  }`

After added some objects and drawEtiqueta is `true` I got this
![image](https://user-images.githubusercontent.com/6618257/40636289-f752dcb4-62c3-11e8-9ddf-3a554e1139a3.png)

But when drawEtiqueta is `false`
`public void keyPressed() {
  switch (key) {
    case 'e':
      nodos.setDrawEtiqueta(!nodos.drawEtiqueta());
      break;
`
I got this, with the same objects quantity
![image](https://user-images.githubusercontent.com/6618257/40636332-19569120-62c4-11e8-9d01-dbe4bd416b97.png)

I got an "additional item !" I store the objects in a ArrayList and the `size()` did no change.
![image](https://user-images.githubusercontent.com/6618257/40636405-6827cf9e-62c4-11e8-8981-e512e5d2f0d9.png)

**Comment by nakednous** [comment]
can't reproduce the issue

**Comment by rvcristiand** [comment]
I made a mistake. I re-make the code and there is not problem.
